config/routes.rb
Rails.application.routes.draw do
  resources :registries
  resources :coordinators
  resources :participants
  resources :enrollments
  get 'home/index'

  root 'home#index'
end

app/models/participant.rb
class Participant < ApplicationRecord
  
  validates :name, :gender, :date_of_birth, presence: true
  
  has_many :enrollments
  has_many :registries, through: :enrollments

  enum gender: [ :male, :female ]
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: %i[ show edit update destroy ]

  # GET /participants or /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1 or /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants or /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully created." }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1 or /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully updated." }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1 or /participants/1.json
  def destroy
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url, notice: "Participant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participant_params
      params.require(:participant).permit(:name, :gender, :date_of_birth)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: participant) do |form| %>
      <% if participant.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

          <ul>
            <% participant.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :gender, style: "display: block" %>
        <%= form.select :gender, Participant.genders.keys, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :date_of_birth, style: "display: block" %>
        <%= form.date_field :date_of_birth, class: "form-control" %>
      </div>
      <br />
      <div>
        <%= form.submit 'Create Participant', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="col-6">
  </div>
</div>

app/views/participants/_participant.html.erb
<div id="<%= dom_id participant %>">
  <p>
    <strong>Name:</strong>
    <%= participant.name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= participant.gender %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= formatted_date(participant.date_of_birth) %>
  </p>

</div>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Show", @participant %> |
  <%= link_to "Back", participants_path %>
</div>

app/views/participants/index.html.erb
<p style="color: green"><%= notice %></p>

<h2>Participants</h2>
<div id="participants">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Gender</th>
        <th>DOB</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @participants.each do |participant| %>
        <tr>
          <td><%= participant.name %></td>
          <td><%= participant.gender %></td>
          <td><%= formatted_date(participant.date_of_birth) %></td>
          <td><%= link_to "Show", participant %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New participant", new_participant_path %>

app/views/participants/new.html.erb
<h2>New participant</h2>

<%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @participant %>

<div>
  <%= link_to "Edit", edit_participant_path(@participant) %> |
  <%= link_to "Back", participants_path %> |
  <%= link_to "Destroy", @participant, method: :delete %>
</div>