config/routes.rb
Rails.application.routes.draw do
  resources :registries
  resources :coordinators
  resources :participants
  resources :enrollments
  get 'home/index'

  root 'home#index'
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  
  validates :participant_id, uniqueness: { scope: :registry_id }
  
  belongs_to :coordinator
  belongs_to :registry
  belongs_to :participant
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:date_of_enrollment, :method_of_contact, :remarks, :coordinator_id, :registry_id, :participant_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
  def registry_options
    options_for_select(Registry.all.map { |r| [r.name, r.id] })
  end

  def participant_options
    options_for_select(Participant.all.map { |r| [r.name, r.id] })
  end

  def coordinator_options
    options_for_select(Coordinator.all.map { |r| [r.name, r.id] })
  end

  def contact_method_options
    options_for_select([['Phone', 'contact_via_phone'], ['Email', 'contact_via_email']])
  end
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
    <strong>Date of enrollment:</strong>
    <%= formatted_date(enrollment.date_of_enrollment) %>
  </p>

  <p>
    <strong>Method of contact:</strong>
    <%= enrollment.method_of_contact %>
  </p>

  <p>
    <strong>Remarks:</strong>
    <%= enrollment.remarks %>
  </p>

  <p>
    <strong>Coordinator:</strong>
    <%= enrollment.coordinator_id %>
  </p>

  <p>
    <strong>Registry:</strong>
    <%= enrollment.registry_id %>
  </p>

  <p>
    <strong>Participant:</strong>
    <%= enrollment.participant_id %>
  </p>

</div>

app/views/enrollments/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: enrollment) do |form| %>
      <% if enrollment.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

          <ul>
            <% enrollment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :date_of_enrollment, style: "display: block" %>
        <%= form.date_field :date_of_enrollment, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :method_of_contact, style: "display: block" %>
        <%= form.select :method_of_contact, contact_method_options %>
      </div>
 
      <div class="form-group">
        <%= form.label :remarks, style: "display: block" %>
        <%= form.text_area :remarks, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :coordinator_id, style: "display: block" %>
        <%= form.select :coordinator_id, coordinator_options, { multiple: true } %>
      </div>

      <div class="form-group">
        <%= form.label :registry_id, style: "display: block" %>
        <%= form.select :registry_id, registry_options, { multiple: true } %>
      </div>

      <div class="form-group">
        <%= form.label :participant_id, style: "display: block" %>
        <%= form.select :participant_id, participant_options, { multiple: true } %>
      </div>
      <br>
      <div class="form-group">
        <%= form.submit 'Submit', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="col-6">
  </div>
</div>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<p style="color: green"><%= notice %></p>

<h2>Enrollments</h2>
<div id="enrollments">
  <table>
    <thead>
      <tr>
        <th>Date of enrollment</th>
        <th>Method of contact</th>
        <th>Remarks</th>
        <th>Coordinator</th>
        <th>Registry</th>
        <th>Participant</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @enrollments.each do |enrollment| %>
        <tr>
          <td><%= formatted_date(enrollment.date_of_enrollment) %></td>
          <td><%= enrollment.method_of_contact %></td>
          <td><%= enrollment&.remarks %></td>
          <td><%= enrollment.coordinator.name %></td>
          <td><%= enrollment.registry.name %></td>
          <td><%= enrollment.participant.name %></td>
          <td><%= link_to "Show", enrollment %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/new.html.erb
<h2>New enrollment</h2>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrollment %>

<div>
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> |
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>